-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg6fDDz6wWChE/n6RvlSy1SJsztNNoCQ/fdCvZxPEmUdKgCgYIKoZIzj0DAQehRANCAATG/dNFG6Bk3+qn3LvWhsjQv9nMFvY29SL1TK3THl//Guq2Z0OUbUC1+mhwSAB5PCFbWZ9uIQhmIzGPxNxKoodu
-----END PRIVATE KEY-----